name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Prefer the built-in GitHub token to avoid missing PAT secret
          token: ${{ secrets.GITHUB_TOKEN }}

          # Output file to keep consistent with repo
          filename: github-metrics.svg

          # Options
          user: Penryn
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Shanghai
